SELECT * FROM employees WHERE salary >= '20000';

SELECT SYSDATE - '24/06/12' FROM DUAL;
--SELECT * FROM employees WHERE hire_date >= '

SELECT first_name, TO_CHAR(hire_date, 'YYYY"년" MM"월" DD "일"') HIREDATE
FROM employees;


SELECT TO_CHAR (SYSDATE, 'YYYY-MM-DD HH:MI:SS') AS 시간 FROM DUAL;
SELECT TO_CHAR (SYSDATE, 'YYYY-MM-DD AM HH:MI:SS') AS TIME FROM DUAL;

SELECT TO_CHAR (SYSDATE, ' YY"년" MM"월" ') AS TIME FROM DUAL;


SELECT TO_CHAR (1372.17 , 'L999,999,999.999') AS RESULT FROM DUAL;


SELECT TO_CHAR (TO_DATE('240613'),  '"20"YY"년" MM "월" DD "일" ') FROM DUAL;

SELECT DECODE (
