CREATE TABLE MEMBER(
    ID VARCHAR2(3) PRIMARY KEY,
    PW VARCHAR2(30),
    AGE NUMBER(3),
    EMAIL VARCHAR2(30)
);

DROP TABLE MEMBER;

DELETE FROM MEMBER WHERE ID ='ABC';

SELECT * FROM member;
--INSERT INTO MEMBER VALUES(값,값,값,값);

INSERT INTO member VALUES ('AAA','AAA',10,'AAA');
INSERT INTO member VALUES ('BBB','BBB',10,'BBB');
INSERT INTO member VALUES ('CCC','CCC',10,'CCC');
INSERT INTO member VALUES ('DDD','DDD',10,'DDD');

COMMIT;

